#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/puppetlabs/bin

. /etc/build_custom_config

if [ "${ENVIRONMENT}" = "" ]
then
    environment=production
else
    environment=${ENVIRONMENT}
fi

download=0
roleOptions="base chef docker jenkins wordpress mailhub nagios kubernetes squid"
progname=$(basename $0)
USAGE="
${progname}: [-h] [-e <environment>] [-n] [-v <version>] [-N]

	-e	Environment (default=${environment})

	-n	Run in noop mode

	-N	New Download Of Puppet Code

	-r	Role (Default $ROLE - Options = ${roleOptions})

	-h	Help

"

# Process Command line args
#

while getopts ":hnr:e:N" nextarg  >/dev/null 2>&1
do
        case $nextarg in
                "h")    echo -e "$USAGE"
			exit 0
                        ;;
                "N")    download=1
                        ;;
                "e")    environment=${OPTARG}
                        ;;
                "r")    ROLE=${OPTARG}
                        ;;
                "n")    noop="--noop"
                        ;;
                *)      echo "Error: flag -${OPTARG} not supported or used without an argument"
                        exit 1
                        ;;
        esac
done
shift_ind=$(expr $OPTIND - 1)
shift $shift_ind

if [ "${ROLE}" = "" ]
then
	ROLE="base"
fi

case $ROLE in
	"base")         role="include role::base_build"
                    ;;
	"chef")         role="include role::chef_build"
                    ;;
	"squid")        role="include role::squid_build"
                    ;;
	"docker")       role="include role::docker_build"
                    ;;
	"nagios")       role="include role::nagios_build"
                    ;;
	"jenkins")      role="include role::jenkins_build"
                    ;;
	"mailhub")      role="include role::mailhub_build"
                    ;;
	"wordpress")    role="include role::wordpress_build"
                    ;;
	"kubernetes")   role="include role::kubernetes_build"
                    ;;
	*)              echo "Error: Role ${OPTARG} not supported"
                    exit 1
                    ;;
esac

distro=$(lsb_release -i | awk '{print $3}')
release=$(lsb_release -r | awk '{print $2}')
if [ "${distro}" == "CentOS" -a "${release}" == "9" ]
then
    distro="CentOS9"
fi

case ${distro} in
    CentOS|RedHatEnterpriseServer)          module_dir=/etc/puppetlabs/puppet/code/environments/${environment}/modules
                                            ;;
    CentOS9|AmazonAMI|Ubuntu)               module_dir=/etc/puppet/environments/${environment}/modules
                                            ;;
    "*")                                    echo "Error: Distribution ${distro} not supported"
                                            exit 1
                                            ;;
esac

echo -e "\nInfo: Building a $ROLE server from the ${environment} repository\n"

if [ ${download} -eq 1 ]
then
	cd ${module_dir}
	git pull
	cd /etc/git/config
	git pull
fi

puppet apply -t ${noop} --modulepath=${module_dir} -e "${role}"

